docker_data_dir: /app/docker_data
keepalived_masterIP: 192.168.2.190
keepalived_slaveIP: 192.168.2.191
keepalived_master_routerid: LVS_DEVEL1
keepalived_slave_routerid: LVS_DEVEL2
keepalived_master_interface: ens33
keepalived_slave_interface: ens33
keepalived_virtual_router_id: "51"
keepalived_master_priority: "100"
keepalived_slave_priority: "80"
keepalived_auth_pass: "1111"
keepalived_vip: 192.168.2.100
keepalived_web01: 192.168.2.192
keepalived_web01_port: "80"
keepalived_web02: 192.168.2.193
keepalived_web02_port: "80"
nfs_share_dir: /app/share
nfs_ipv6_disabled: true
