version: '3'

services:
  prometheus:
    image: ${prometheus_image}
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  alertmanager:
    image: ${alertmanager_image}
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    restart: always

  grafana:
    image: ${grafana_image}
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/default-provider.yaml:/etc/grafana/provisioning/dashboards/default-provider.yaml
      - ./dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${grafana_user}
      - GF_SECURITY_ADMIN_PASSWORD=${grafana_password}
      - prometheus_url=${prometheus_url}
    restart: always

  pushgateway:
    image: ${pushgateway_image} 
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: always

  blackbox-exporter:
    image: ${blackbox_image}
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    restart: always

  node-exporter:
    image: ${nodeexporter_image}
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always

volumes:
  grafana_data:    
